name: board

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql-5.7-container
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: board
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    restart: no
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_PASSWORD=password
    command: >
      bash -c "
        bin/elasticsearch-plugin remove analysis-nori;
        bin/elasticsearch-plugin install analysis-nori;
        bin/elasticsearch
      "
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    restart: no
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.0
    container_name: logstash
    restart: no
    environment:
      - xpack.monitoring.enabled=false
      - LOGSTASH_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./logstash_data/pipeline:/usr/share/logstash/pipeline
      - ./logstash_data/mysql-connector-j-9.0.0.jar:/usr/share/logstash/mysql-connector-j-9.0.0.jar
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - mysql
      - elasticsearch

volumes:
  mysql-data:
  es_data:
    driver: local